### ISSUE TITLE
AdvUtils.DoubleArrayTrieSearch does not have Load Method

### ISSUE THREAD

**Issue by rezkaaufar** [zhongkaifu/CRFSharp#14]
Hi,

I am trying to implement a CRF Decoder with this wonderful library in C#, but I got an error when I tried to load the model with DecoderWrapper.
`var crfWrapper = new CRFSharpWrapper.Decoder();`
`crfWrapper.LoadModel(options.strModelFileName);`

The error I got is 
`System.MissingMethodException: 'Method not found: 'Void AdvUtils.DoubleArrayTrieSearch.Load(System.String)'.'`

I use your latest AdvUtils.dll but I still have the error. I installed your package from NuGET.
Could you help me?
Thank you very much

**Comment by zhongkaifu** [comment]
Hi @rezkaaufar ,

That's because the latest AdvUtils.dll is not the correct version used by CRFSharp.dll

I suggest you check out the latest CRFSharp and AdvUtils code. Build AdvUtils project at first, and copy AdvUtils.dll to dll folder in CRFSharp project, then build CRFSharp project. It should resolve your problem.

**Comment by rezkaaufar** [comment]
It works now, thank you very much for your help @zhongkaifu 👍
